---
- name: '[resolv] Check if "i" file attribute for /etc/resolv.conf is set'
  shell: lsattr /etc/resolv.conf | cut -d ' ' -f 1 | grep -q "i"
  register: rpi_espandfs_resolv_conf_attrib_i
  changed_when: false
  failed_when: false
  tags:
    - resolv

- name: '[resolv] Unlock /etc/resolv.conf before changing nameserver, if it was locked'
  command: chattr -i /etc/resolv.conf
  become: yes
  when: rpi_espandfs_resolv_conf_attrib_i.rc == 0
  tags:
    - resolv

- name: '[resolv] Temporarily set dns to 9.9.9.9 in order to resolve *.raspberrypi.org'
  copy: src=resolv.conf dest=/etc/resolv.conf mode=0644 owner=root group=root
  become: yes
  tags:
    - resolv
...
